// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var app;

  app = angular.module('app', ['ngRoute', 'ui.bootstrap', 'restangular', 'SiteModule']);

  app.config([
    '$routeProvider', '$locationProvider', 'RestangularProvider', function($routeProvider, $locationProvider, RestangularProvider) {
      RestangularProvider.setBaseUrl('/api/v1');
      $routeProvider.otherwise({
        redirectTo: '/'
      });
      if (window.history && window.history.pushState) {
        return $locationProvider.html5Mode(true);
      }
    }
  ]);

}).call(this);
